name: sync-code

on:
  workflow_dispatch:
#  schedule:
#    - cron: '*/30 0-16,22-23 * * *'

jobs:
  build:
    runs-on: Ubuntu-20.04
    steps:
    
    - name: Init Build Dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        git config --global user.name 'GitHub Actions' 
        git config --global user.email 'noreply@github.com'
    - name: Prepare
      run: |
        mkdir -p ~/.ssh
        echo -e "${{ secrets.SSH_JD }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan gitee.com > ~/.ssh/known_hosts
    - name: Clone Master
      run: |
        git clone -b master https://github.com/fichenx/flede.git main
    - name: Push Dust
      uses: ad-m/github-push-action@master
      with:
        directory: master
        github_token: ${{ secrets.PAT }}
        branch: master
